logDir : "/work/haskell/pms/pty-mcp-server/logs"
logLevel : "Debug"
toolsDir : "/work/haskell/pms/pty-mcp-server/assets/tools"
prompts:
  - "ghci>"
  - "]#"
  - "]$"
  - ")?"
  - "password:"
