logDir : "/work/haskell/pms/pty-mcp-server/logs"
logLevel : "Debug"
workDir : "/work/haskell/pms/pty-mcp-server/assets"
toolsDir : "/work/haskell/pms/pty-mcp-server/assets/tools"
promptsDir : "/work/haskell/pms/pty-mcp-server/assets/prompts"
resourcesDir : "/work/haskell/pms/pty-mcp-server/assets/resources"
prompts:
  - '>>>'
  - ']#'
  - ']$'
  - ')?'
  - 'Password:'
  - 'password:'
  - 'ghci>'

# not yet implemented parameters.
environment:
  ProgramData: "C:\\ProgramData"
  SystemRoot: "C:\\Windows"
timeoutMicrosec: 1000000
invalidChars:
  - '&&'
  - '||'
  - '|'
  - '..'
invalidWinCmds:
  - del
  - erase
  - rd
  - rmdir
  - format
  - shutdown
  - restart
  - taskkill
invalidLinuxCmds:
  - rm
  - mv
  - dd
  - chmod
  - chown
  - shutdown
  - reboot
  - kill
  - nc
