logDir : "/work/haskell/pms/pty-mcp-server/logs"
logLevel : "Debug"
workDir : "/work/haskell/pms/pty-mcp-server/assets"
toolsDir : "/work/haskell/pms/pty-mcp-server/assets/tools"
promptsDir : "/work/haskell/pms/pty-mcp-server/assets/prompts"
resourcesDir : "/work/haskell/pms/pty-mcp-server/assets/resources"
prompts:
  - '>>>'
  - ']#'
  - ']$'
  - ')?'
  - 'Password:'
  - 'password:'
  - 'ghci>'
